# fly.toml app configuration file generated for bluesky-contributors-feed-empty-star-8516 on 2024-11-21T01:35:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bluesky-contributors-feed-empty-star-8516'
primary_region = 'lax'

[build]

[env]
  FEEDGEN_SQLITE_LOCATION = "/data/sqlite.db"
  FEEDGEN_HOSTNAME = "bluesky-contributors.horus.dev"
  FEEDGEN_LISTENHOST = "0.0.0.0"
  FEEDGEN_PUBLISHER_DID = "did:plc:pe5lhpot2jvtxribylimv2is"

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 8
